#######################################
# 공통 설정
#######################################
server:
  port: 0

spring:
  profiles:
    active: local

  messages:
    basename: i18n/messages
    cache-duration: -1
  session:
    timeout: 24h